### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by SkyBulk** [bricesuazo/eboto-mo#10]
### Describe the feature you'd like to request

it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used?

### Describe the solution you'd like to see

it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used?

**Comment by bricesuazo** [comment]
Thank you for your interest!

License added. [https://github.com/bricesuazo/eboto-mo/blob/main/LICENSE](https://github.com/bricesuazo/eboto-mo/blob/main/LICENSE)
